name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4

    - name: Delete container if it exists
      run: docker stop davids-game-api

    - name: Delete container if it exists
      run: docker rm davids-game-api
    
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag davids-game-api

    - name: Run the Docker image
      run: docker run -d --name davids-game-api --mount source=fpl,target=/fpl -p 8080:8080/tcp -p 8081:8081/tcp davids-game-api
